### ISSUE TITLE
Getting exception trying to run the script

### ISSUE THREAD

**Issue by devna13** [beaunorgeot/philter_ucsf#3]
When I'm executing philter.py I'm getting this error: 
any ideas?

(base) C:\Users\na>py "C:\na\code\philter_ucsf-master\philter.py" -i "C:\na\code\philter_ucsf-master\samplePHI.txt" -o "C:\na\code\philter_ucsf-master\redacted"
input file: C:\na\code\philter_ucsf-master\samplePHI.txt
output folder: C:\na\code\philter_ucsf-master\redacted
Using whitelist: C:\na\code\philter_ucsf-master\whitelist.pkl
length of whitelist: 290052
phi_reduced file's name would be: samplePHI_phi_reduced.txt
run in 1 process(es)
samplePHI.txt
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\na\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\na\code\philter_ucsf-master\philter.py", line 431, in filter_task
    sent_tag = nltk.pos_tag_sents(sent)
  File "C:\Users\na\AppData\Local\Continuum\anaconda3\lib\site-packages\nltk\tag\__init__.py", line 180, in pos_tag_sents
    return [_pos_tag(sent, tagset, tagger) for sent in sentences]
  File "C:\Users\na\AppData\Local\Continuum\anaconda3\lib\site-packages\nltk\tag\__init__.py", line 180, in <listcomp>
    return [_pos_tag(sent, tagset, tagger) for sent in sentences]
  File "C:\Users\na\AppData\Local\Continuum\anaconda3\lib\site-packages\nltk\tag\__init__.py", line 115, in _pos_tag
    "Currently, NLTK pos_tag only supports English and Russian "
NotImplementedError: Currently, NLTK pos_tag only supports English and Russian (i.e. lang='eng' or lang='rus')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\na\code\philter_ucsf-master\philter.py", line 683, in <module>
    main()
  File "C:\na\code\philter_ucsf-master\philter.py", line 661, in main
    results_list = [r.get() for r in results]
  File "C:\na\code\philter_ucsf-master\philter.py", line 661, in <listcomp>
    results_list = [r.get() for r in results]
  File "C:\Users\na\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
NotImplementedError: Currently, NLTK pos_tag only supports English and Russian (i.e. lang='eng' or lang='rus')

(base) C:\Users\na>

**Comment by devna13** [comment]
I was missing some stuff

updating nltk resolved the issue

conda install -c anaconda nltk
